# Generated by Django 2.1.1 on 2018-11-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('father', models.CharField(max_length=30)),
                ('roll', models.IntegerField(unique=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Board')),
            ],
        ),
    ]
