# Generated by Django 2.1.1 on 2018-11-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='gpa',
            field=models.CharField(default='A+', max_length=30),
            preserve_default=False,
        ),
    ]
